Page titles component
wolox-training/abh-react pull request #2
Opened 2018-09-20 19:57 UTC by alejobh

## Summary

The purpose of this branch is to add the Component pageTitle, check the screenshot.

## Screenshots

![image](https://user-images.githubusercontent.com/15016271/45843275-c6e10080-bce4-11e8-8a71-fa07d919fe7e.png)

## Known isssues/Notes

The first branch pushed was called ‘proyect-setup‘ Link: https://github.com/wolox-training/abh-react/tree/proyect-setup didn't contain the assets folder so i included it in this new branch and i also updated the .gitignore to ignore the actual files that needed to be ignored and removed from the branch

## Trello Card

https://trello.com/c/1nLnKBH3

2018-09-20 21:37 UTC, henryzarza requested changes

2018-09-20 21:37 UTC, henryzarza commented on maquetado/scss/application.scss
> +	font-family: $font-family;
The indentation it's must be 2 spaces

2018-09-20 21:37 UTC, henryzarza commented on maquetado/scss/titles.scss
> +  height: $title-decoration-height;
Remember the properties must be order by alphabetically

2018-09-20 21:37 UTC, henryzarza commented on maquetado/scss/titles.scss
> +    background: (url(assets/triangle.svg));
It's not necessary wrapper `(url(assets/triangle.svg))` you just put `url(assets/triangle.svg)` and below you have the property `background-repeat` so I consider that you should change the currently property `background` for `background-image`

2018-09-20 21:37 UTC, henryzarza commented on maquetado/scss/titles.scss
> +
Delete this line empty

2018-09-21 12:43 UTC, braiandickson commented
@alejobh, resolve conflicts updating your branch with the last merge 👍

2018-09-21 15:51 UTC, henryzarza approved these changes

2018-09-21 15:51 UTC, merged