Services - Redux-Form- Apisauce
wolox-training/abh-react pull request #20
Opened 2018-10-12 23:40 UTC by alejobh

## Summary
Added redux forms with vali
Added Login Layout
Added Apisauce
The API is on Loopback.

## Screenshots
![image](https://duaw26jehqd4r.cloudfront.net/items/3v2R011e2u472z3b1l2G/Screen%20Recording%202018-10-12%20at%2006.39%20PM.gif?v=67be596b)

## Trello cards
https://trello.com/c/qXR628cx

2018-10-16 17:27 UTC, jmtov requested changes
Awesome job, Alejo! I just added some comments. Please review them! 👍

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/index.js
> +        className={`${styles.formInput} ${calculateErrorClass()}`}
I'd recommend that you use inline validation in this case. Remember not to define functions within Stateless components. :)

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/styles.scss
> +    transform: scale(1.04, 1.04);
You can just use `scale(1.04)` here.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/styles.scss
> +  transform-style: preserve-3d;
What are you using this `preserve-3d` for?

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/styles.scss
> +      transform: translate3d(-1px, 0, 0);
If you won't trigger anything in the `z axis` you can use `translate()`.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/styles.scss
> +  text-align: left;
Is this necessary for the label to display properly? If not, please remove it.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Form/Input/styles.scss
> +  text-align: left;
Same comment in the label.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/components/Logo/styles.scss
> +    transform: scale(1, 1) rotate3d(0, 0, 0, 0);
You can simplify the `scale` function here too.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/screens/Login/components/LoginForm/styles.scss
> +    transform: scale(1, 1);
Remember the simplified `scale` function.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/constants/redux.js
> +export const LOGIN_ACTIONS = {
I would recommend moving the action types to the actions file of each store entry.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/redux/auth/actions.js
> +  initApp: () => async dispatch => {
Does this function need to be `async`?

2018-10-16 17:27 UTC, jmtov commented on react/game/src/services/authService.js
> +  post: values => API.post(API_LOGIN_PATH, { email: values.email, password: values.password })
What about destructuring the `values` object to get only `email` and `password`?

2018-10-16 17:27 UTC, jmtov commented on react/game/src/utils/router.js
> +    if (routeToCheck[key].path === pathname) return true;
I think you can turn this into a ternary expression.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/validation/forms/index.js
> +  const inputName = rest[2];
Identify this `2` with a descriptive name like `inputNameIndex` or something that gives you an idea what this index is for.

2018-10-16 17:27 UTC, jmtov commented on react/game/src/app/screens/Game/index.js
> +      saveGameState(store.getState().game);
Nice approach! 😺

2018-10-16 18:43 UTC, alejobh commented on react/game/src/app/components/Form/Input/index.js
> +        className={`${styles.formInput} ${calculateErrorClass()}`}
Perfect 👌🏼

2018-10-16 18:44 UTC, alejobh commented on react/game/src/app/components/Form/Input/styles.scss
> +  text-align: left;
It is not 🤦🏻‍♂️

2018-10-16 18:50 UTC, alejobh commented on react/game/src/redux/auth/actions.js
> +  initApp: () => async dispatch => {
No, in this moment this does not need to be `async` thx for the comment 👌🏼

2018-10-16 18:51 UTC, alejobh commented on react/game/src/services/authService.js
> +  post: values => API.post(API_LOGIN_PATH, { email: values.email, password: values.password })
👌🏼

2018-10-16 18:53 UTC, alejobh commented on react/game/src/validation/forms/index.js
> +  const inputName = rest[2];
Thanks for the comment 👌🏼

2018-10-16 19:03 UTC, jmtov submitted a review, later dismissed

2018-10-16 20:13 UTC, wfolini requested changes
Excellent PR. Just some small changes and go!

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/components/Dashboard/index.js
> +import ROUTES from '@constants/routes';
```suggestion
import routes from '@constants/routes';
```
Since routes is a object, not a constant.

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/components/AuthRoute/index.js
> +import { func, bool } from 'prop-types';
I recommend not applying the prop-types destructuring because it goes against the use of snippets

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/components/Form/Input/index.js
> +import { string, shape } from 'prop-types';
Same

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/index.js
> +import { func, shape } from 'prop-types';
Same

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/screens/Game/index.js
> +      saveGameState(store.getState().game);
👌

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/screens/Login/components/LoginForm/index.js
>  import { FORM_NAMES } from '@constants/formNames';
Why not just a export default of this file?

2018-10-16 20:13 UTC, wfolini commented on react/game/src/app/screens/Login/components/LoginForm/index.js
> +    <form className={styles.loginForm} onSubmit={handleSubmit(onSubmit)}>
Just `onSubmit={handleSubmit}>`

2018-10-16 20:13 UTC, wfolini commented on react/game/src/redux/auth/actions.js
> +    dispatch(privateActionCreators.loginLoading(false));
i'd dispatch this actions at the end of this func

2018-10-16 20:13 UTC, wfolini commented on react/game/src/services/authService.js
> +import { API_LOGIN_PATH } from '@constants/apiNames';
Why u need to extract api names to external file? if it is in this file I do not see it wrong

2018-10-16 20:13 UTC, WFolini commented on react/game/src/utils/auth.js
> +export { loadAuthState, saveAuthState };
I'd move all this to `localStorageService` file, and I'd convert `get`, `set` and `delete` to private functions

2018-10-16 22:11 UTC, alejobh commented on react/game/src/app/components/AuthRoute/index.js
> +import { func, bool } from 'prop-types';
Thanks for your comment, I'll take it from now on 👌🏼

2018-10-16 22:14 UTC, alejobh commented on react/game/src/app/components/Dashboard/index.js
> +import ROUTES from '@constants/routes';
Copy that.

2018-10-16 22:20 UTC, alejobh commented on react/game/src/app/screens/Login/components/LoginForm/index.js
> +    <form className={styles.loginForm} onSubmit={handleSubmit(onSubmit)}>
I know now that the name of the function `onSubmit` is automatically called by redux-form 👌🏼

2018-10-17 16:32 UTC, wfolini approved these changes

2018-10-17 16:33 UTC, WFolini commented
@alejobh  👏 👏

2018-10-17 16:37 UTC, merged