Css transition
wolox-training/abh-react pull request #5
Opened 2018-09-21 15:38 UTC by alejobh

## Summary
A CSS Transition has been added to the Tech card.

## Screenshots

![image](https://user-images.githubusercontent.com/15016271/45891134-6906f400-bd8a-11e8-8b0e-ebfad6cf7197.png)

## Trello Card
https://trello.com/c/AHGq7QwF

2018-09-21 23:17 UTC, henryzarza requested changes

2018-09-21 23:17 UTC, henryzarza commented on maquetado/application.css
> +
Add this file the `gitignore`

2018-09-21 23:17 UTC, henryzarza commented on maquetado/scss/tech.scss
> +@import "variables";
Remember the good practices in [css-style-guide](https://github.com/Wolox/tech-guides/blob/master/frontend/docs/css-style-guide.md#quotes)

2018-09-21 23:17 UTC, henryzarza commented on maquetado/scss/tech.scss
>      margin: 15px 15px;
I think a good approach is that you apply the shorthand `margin: 15px`

2018-09-21 23:17 UTC, henryzarza commented on maquetado/scss/variables.scss
> +$tech-transition: top 0.2s linear, left 0.2s linear;
I think that not it's necessary create a variable because you only use it once

2018-09-24 14:46 UTC, braiandickson approved these changes

2018-09-24 14:51 UTC, henryzarza approved these changes

2018-09-24 14:56 UTC, merged